### ISSUE TITLE
feat: add move description

### ISSUE THREAD

**Issue by Vaalley** [Vaalley/pokemouille#2]
add move description on pokemons page, just like abilities

**Comment by Masch90** [comment]
Hey I am interested in working on this.
Can you clarify for me what is meant by abilities description that should be the blueprint for the moves description?

**Comment by Vaalley** [comment]
> Hey I am interested in working on this. Can you clarify for me what is meant by abilities description that should be the blueprint for the moves description?

Hey, sorry, I just did that last night, if you want you can check the last commit to see how I did it. It's very nice of you to come here and try to help though. I'll mark this issue as closed now.
